function computeGridHaltonAnsKey(n,b1,b2)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Carlos Torres, May 1, 2011
% Updated by Patrick Therrien, May 13, 2015
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% For an input number of points in the unit square X = [0, 1]2 in the plane 
% this code plots 
% the 2-dimensional Halton sequence generated by prime numbers b1 and b2. 

% Given:
d = 2; l = n ^ (1/d);


% Halton Base1
base = b1;  S_base2 = zeros (1,n);

for i = 1:n
    f     = 1/base;    
    itmp  = i;
    x     = 0;
while(itmp>0)
    q     = floor(itmp/base);
    r     = rem(itmp,base);
    x     = x + f * r;
    itmp  = q;
    f     = f/base;
end
    S_base2 (i) = x;
end


% Halton Base2
base = b2;
S_base3   = zeros (1,n);

for i = 1:n
    f     = 1/base;    
    itmp  = i;
    x     = 0;
while(itmp>0)
    q     = floor(itmp/base);
    r     = rem(itmp,base);
    x     = x + f * r;
    itmp  = q;
    f     = f/base;
end
    S_base3 (i) = x;
end

% plot the coordinate pairs: (HaltonSequenceBase2, HaltonSequenceBase3)
hold on;
for Index = 1:n;
    plot(S_base2(Index),S_base3(Index),'*g','LineWidth',1,'MarkerSize',3);
end
set (gca, 'YTick', 0:1/l:1); set (gca, 'XTick', 0:1/l:1);
grid on; hold off; title ('Halton Grid');
end
