%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Intro to Robotics, ME170A/ECE181A, Spring 2011
% Carlos Torres
% May 1, 2011
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% For n = 100 in the unit square X = [0, 1]2 in the plane 
% this code plots the following sample sets: 
% 1. the uniform Sukharev center grid, 
% 2. a random uniformly generated with MATLAB command rand, and 
% 3. the 2-dimensional Halton sequence generated by prime numbers 2 and 3. 


clear all; close all; clc;
%% Sukharev Grid
% given:
n = 100;
d = 2;
l = n ^ (1/d);

% set the ranges
i = 1:l;
j = 1:l;

% This could be done as a single mesh operation; however, this might be
% easier follow. P := point
P_i = (1/(2*l)) * ((2*i)-1);
P_j = (1/(2*l)) * ((2*i)-1); %NOTE: P_j = P_i

% plot single markers for each coordinate pair (P_i,P_j)
figure()
hold on;
for Index_i=1:l
    for Index_j=1:l
        plot(P_i(Index_i),P_j(Index_j),'*b','LineWidth',1,'MarkerSize',3);
    end
end
% set the tick lines for the grid
set (gca, 'YTick', [0:1/l:1]);
set (gca, 'XTick', [0:1/l:1]);
grid on;
hold off;
title ('Sukharev or Center Grid');


%% Pseudo Randomly Grid
Rand_P = rand(n,d);
% Note: Each of the columns 'd' represents an element of the coordinate
% pair. 

% plot single markers for each coordinate pair 
%               (Rand_P(index,1),Rand_P(index,1))
figure()
hold on;
for Index = 1: n;
    plot(Rand_P(Index,1),Rand_P(Index,2),'*r','LineWidth',1,'MarkerSize',3);
end
set (gca, 'YTick', [0:1/l:1]);
set (gca, 'XTick', [0:1/l:1]);
grid on;
hold off;
title ('Pseudo-Random Grid')

%% Halton Sequence Grid
N =100; % common to both

% Halton Base = 2
base = 2;
S_base2   = zeros (1,N);

for i = 1:N
    f     = 1/base;    
    itmp  = i;
    x     = 0;
while(itmp>0)
    q     = floor(itmp/base);
    r     = rem(itmp,base);
    x     = x + f * r;
    itmp  = q;
    f     = f/base;
end
    S_base2 (i) = x;
end


% Halton Base = 3
base = 3;
S_base3   = zeros (1,N);

for i = 1:N
    f     = 1/base;    
    itmp  = i;
    x     = 0;
while(itmp>0)
    q     = floor(itmp/base);
    r     = rem(itmp,base);
    x     = x + f * r;
    itmp  = q;
    f     = f/base;
end
    S_base3 (i) = x;
end

% plot the coordinate pairs: (HaltonSequenceBase2, HaltonSequenceBase3)
figure()
hold on;
for Index = 1:N;
    plot(S_base2(Index),S_base3(Index),'*g','LineWidth',1,'MarkerSize',3);
end
set (gca, 'YTick', [0:1/l:1]);
set (gca, 'XTick', [0:1/l:1]);
grid on;
hold off;
title ('Halton Grid');


